### ISSUE TITLE
9ED Localized in Korean

### ISSUE THREAD

**Issue by csuhta** [scryfall/gatherer-bugs#46]
Ninth Edition has been localized in Korean on Gatherer, but no such cards physically exist

**Comment by RivalRowan** [comment]
The Korean localization appears to have been removed from the new Gatherer as of September 2, 2025.
This issue has been fixed.

**Examples:**
Angel of Mercy (https://gatherer.wizards.com/9ED/en-us/1/angel-of-mercy)
<img width="1304" height="648" alt="Angel of Mercy (Ninth Edition)" src="https://github.com/user-attachments/assets/757c154e-a827-4b34-a4e5-320b9f6cdb3f" />

Nekrataal (https://gatherer.wizards.com/9ED/en-us/149/nekrataal)
<img width="1295" height="644" alt="Nekrataal (Ninth Edition)" src="https://github.com/user-attachments/assets/909c1522-12f2-49f6-8880-b09c4b634aa8" />

Yavimaya Coast (https://gatherer.wizards.com/9ED/en-us/330/yavimaya-coast)
<img width="1303" height="648" alt="Yavimaya Coast (Ninth Edition)" src="https://github.com/user-attachments/assets/216ea0b3-2a09-4645-8b36-13b7b4cc57ba" />

**Comment by RivalRowan** [comment]
Please note that the Sets page, which displays localized languages, says otherwise but I can't believe that page is correct.

https://gatherer.wizards.com/sets?page=9
<img width="1357" height="1855" alt="Gatherer list of sets with language localizations." src="https://github.com/user-attachments/assets/e3b43540-9fdc-4f6d-af5b-f09ba71cf248" />

**Comment by a-tangible-human-skull** [comment]
This appears to be a piecemeal fix, as there are cards from 9E that still have KO prints.

https://gatherer.wizards.com/9ED/ko-ko/1/eager-cadet

<img width="871" height="591" alt="Image" src="https://github.com/user-attachments/assets/6c9b963b-2a5c-4e8d-8610-d1b710f516c2" />

Marking as still present in current Gatherer
